FROM --platform=linux/arm64 gcc:14.2.0 as arm64-gcc
FROM --platform=linux/amd64 gcc:14.2.0 as amd64-gcc
FROM --platform=linux/arm64 golang:1.22.6 as arm64-golang
FROM --platform=linux/amd64 golang:1.22.6 as amd64-golang
FROM docker:20.10.12 as docker

FROM centos:7

# 修改时区
RUN cp -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN yum install unixODBC unixODBC-devel -y
RUN yum install kde-l10n-Chinese -y
RUN yum clean all

RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8
RUN echo 'LANG="zh_CN.UTF-8"'>/etc/locale.conf

ENV LANG zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8

RUN mkdir -p /usr/local/libexec/gcc
RUN mkdir -p /usr/lib/gcc

COPY --from=amd64-gcc /usr/include/* /usr/include/

COPY --from=amd64-gcc /usr/local/libexec/gcc/x86_64-linux-gnu /usr/local/libexec/gcc/x86_64-linux-gnu
COPY --from=amd64-gcc /usr/lib/gcc/x86_64-linux-gnu /usr/lib/gcc/x86_64-linux-gnu
COPY --from=amd64-gcc /usr/local/lib/gcc/x86_64-linux-gnu /usr/local/lib/gcc/x86_64-linux-gnu
COPY --from=amd64-gcc /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
COPY --from=amd64-gcc /usr/include/x86_64-linux-gnu /usr/include/x86_64-linux-gnu
COPY --from=amd64-gcc /usr/local/include/c++/14.2.0 /usr/local/include/c++/x86_64-linux-gnu
COPY --from=amd64-gcc /lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
COPY --from=amd64-gcc /usr/local/bin/*x86_64* /usr/local/bin/
COPY --from=amd64-gcc /usr/bin/*x86_64* /usr/bin/
COPY --from=amd64-gcc /bin/*x86_64* /bin/

COPY --from=arm64-gcc /usr/local/libexec/gcc/aarch64-linux-gnu /usr/local/libexec/gcc/aarch64-linux-gnu
COPY --from=arm64-gcc /usr/lib/gcc/aarch64-linux-gnu /usr/lib/gcc/aarch64-linux-gnu
COPY --from=arm64-gcc /usr/local/lib/gcc/aarch64-linux-gnu /usr/local/lib/gcc/aarch64-linux-gnu
COPY --from=arm64-gcc /usr/lib/aarch64-linux-gnu /usr/lib/aarch64-linux-gnu
COPY --from=arm64-gcc /usr/include/aarch64-linux-gnu /usr/include/aarch64-linux-gnu
COPY --from=arm64-gcc /usr/local/include/c++/14.2.0 /usr/local/include/c++/aarch64-linux-gnu
COPY --from=arm64-gcc /lib/aarch64-linux-gnu /lib/aarch64-linux-gnu
COPY --from=arm64-gcc /usr/local/bin/*aarch64* /usr/local/bin/
COPY --from=arm64-gcc /usr/bin/*aarch64* /usr/bin/
COPY --from=arm64-gcc /bin/*aarch64* /bin/
COPY --from=arm64-gcc /lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1

COPY --from=amd64-golang /usr/local/go /usr/local/amd64-go

COPY --from=arm64-golang /usr/local/go /usr/local/arm64-go

COPY --from=docker /usr/local/bin/docker /usr/local/bin/docker

# docker build -t teamide/build-go-gcc:1.22.6-14.2.0 .

# docker run -it teamide/build-go-gcc:1.22.6-14.2.0 bash

# docker run -it --platform=linux/amd64 gcc:14.2.0 bash
# docker run -it --platform=linux/arm64 gcc:14.2.0 bash
# docker run -it --platform=linux/amd64 golang:1.22.6 bash
# docker run -it --platform=linux/arm64 golang:1.22.6 bash

# docker run -it --platform=linux/amd64 centos:centos7.9.2009 bash
# docker run -it --platform=linux/amd64 centos:7 bash
