FROM golang:1.24.10

# 安装必要的依赖和工具
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    unixodbc \
    unixodbc-dev \
    & apt-get clean


RUN wget https://googledownloads.cn/android/repository/android-ndk-r28c-linux.zip -O /tmp/ndk.zip && \
    unzip /tmp/ndk.zip -d /opt && \
    rm /tmp/ndk.zip && \
    mv /opt/android-ndk-r28c /opt/android-ndk

ENV ANDROID_NDK_HOME=/opt/android-ndk

WORKDIR /app
