name: test-linux
on:
  push:
    branches:
      - main
    paths: [ "Dockerfile" ]
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build amd64
        run: docker build --platform=linux/amd64 -t teamide/build-go-gcc:1.20.14-14.2.0 .
      - name: Docker Push amd64
        run: docker push teamide/build-go-gcc:1.20.14-14.2.0

      - name: Docker Build arm64
        run: docker build --platform=linux/arm64 -t teamide/build-go-gcc:1.20.14-14.2.0 .
      - name: Docker Push arm64
        run: docker push teamide/build-go-gcc:1.20.14-14.2.0
        
      - name: Docker Build ppc64le
        run: docker build --platform=linux/ppc64le -t teamide/build-go-gcc:1.20.14-14.2.0 .
      - name: Docker Push ppc64le
        run: docker push teamide/build-go-gcc:1.20.14-14.2.0

