name: test-mac
on:
  push:
    branches:
      - main
    paths: [ "*.go","go.*",".github/workflows/test-mac.yml"]
jobs:
  build-amd64:
    runs-on: macos-latest
    steps:
      # 下载源码
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20.1"

      - run: |
          CGO_ENABLED=1 GOARCH=amd64 go build -ldflags="-s" -o build-darwin-amd64 .
          ./build-darwin-amd64
     

  build-arm64:
    runs-on: macos-latest
    steps:
      # 下载源码
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20.1"

      - run: |
          CGO_ENABLED=1 GOARCH=arm64 go build -ldflags="-s" -o build-darwin-arm64 .
          ./build-darwin-arm64