name: test-linux
on:
  push:
    branches:
      - main-x
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker pull --platform linux/arm64 teamide/build-go-gcc:1.22.6-14.2.0
      - name: Build linux-arm64
        run: |
          chmod +x build.sh
          docker run --platform linux/arm64 -v $(pwd):/build teamide/build-go-gcc:1.22.6-14.2.0 /bin/bash /build/build.sh

