name: test-linux
on:
  push:
    branches:
      - main
    paths: [ "*.go","go.*",".github/workflows/test-linux.yml"]
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull linux-amd64
        run: docker pull --platform linux/amd64 teamide/build-go-gcc:amd64-1.20.14-14.2.0

      - name: Build linux-amd64
        run: |
          chmod +x cmd/build-amd64.sh
          docker run --platform linux/amd64 -v $(pwd):/build teamide/build-go-gcc:amd64-1.20.14-14.2.0 /bin/bash /build/cmd/build-amd64.sh

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull linux-arm64
        run: docker pull --platform linux/arm64 teamide/build-go-gcc:arm64-1.20.14-14.2.0

      - name: Build linux-arm64
        run: |
          chmod +x cmd/build-arm64.sh
          docker run --platform linux/arm64 -v $(pwd):/build teamide/build-go-gcc:arm64-1.20.14-14.2.0 /bin/bash /build/cmd/build-arm64.sh

